#!/bin/bash
export TELEGRAM_BOT_TOKEN="8864572723:AAHnULmlYodSFDo81XklG02Qh28FIEeFQ1g"
export TELEGRAM_CHAT_ID="1051997978"
export WEBHOOK_URL="https://proxy-fairfield-midwest-musical.trycloudflare.trycloudflare.com" # fallback to trycloudflare.com
export WEBHOOK_URL="https://proxy-fairfield-midwest-musical.trycloudflare.com"

# Activate virtual environment if it exists
if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

exec uvicorn main:app --host 0.0.0.0 --port 8080 --reload
